name: dungen_manager
description: A new Flutter project.
publish_to: 'none'
version: 1.0.4+4

environment:
  # KORREKTUR: Wir erlauben jede Dart-Version ab 3.0.0. Deine Version 3.9.2 passt da perfekt rein.
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  sqflite:
  sqflite_common_ffi:
  path: 
  image_picker:
  flutter_markdown:
  uuid:
  http: ^1.1.0       # Für den Datenimport von 5e.tools
  provider: ^6.1.2     # Provider für State-Management
  url_launcher: ^6.2.0  # Öffnet Browser/Datei-Manager für Updates
  archive: ^3.4.0       # Zum Entpacken von ZIP-Dateien bei Updates

    # NEUE PAKETE FÜR DAS SOUND-SYSTEM
  file_picker: ^8.0.0+1       # Zum Auswählen von Dateien (unseren MP3s)
  path_provider: ^2.1.4   # Um einen sicheren Speicherort in der App zu finden
  audioplayers: ^6.1.0      # Zum Abspielen der Audio-Dateien

# Hier deine Pakete hinzufügen
  font_awesome_flutter: ^10.7.0 # Oder was auch nicht die neueste Version ist
  flutter_svg: ^2.0.10+1       # Oder was auch nicht die neueste Version ist

  cupertino_icons: ^1.0.2
  ultimate_flutter_icons: ^1.4.0
  
  # MCP Server dependencies
  json_rpc_2: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test: # <--- DIESE ZEILE HINZUFÜGEN
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
