import '../models/creature.dart';
import '../models/attack.dart';
import 'uuid_service.dart';

/// Service für die Erstellung von Creature-Objekten aus verschiedenen Quellen
class CreatureFactoryService {
  /// Erstellt Creature aus offiziellem Monster
  static Creature fromOfficialMonster({
    required String officialMonsterId,
    required String name,
    required int maxHp,
    required int armorClass,
    required String speed,
    required int strength,
    required int dexterity,
    required int constitution,
    required int intelligence,
    required int wisdom,
    required int charisma,
    String? size,
    String? type,
    String? subtype,
    String? alignment,
    int? challengeRating,
    String? specialAbilities,
    String? legendaryActions,
    String? description,
    String? attacks,
    List<Attack>? attackList,
  }) {
    return Creature(
      id: UuidService().generateId(),
      officialMonsterId: officialMonsterId,
      name: name,
      maxHp: maxHp,
      currentHp: maxHp,
      armorClass: armorClass,
      speed: speed,
      strength: strength,
      dexterity: dexterity,
      constitution: constitution,
      intelligence: intelligence,
      wisdom: wisdom,
      charisma: charisma,
      size: size,
      type: type,
      subtype: subtype,
      alignment: alignment,
      challengeRating: challengeRating,
      specialAbilities: specialAbilities,
      legendaryActions: legendaryActions,
      description: description,
      attacks: attacks ?? "",
      attackList: attackList ?? const [],
      isCustom: false,
      sourceType: 'official',
      sourceId: officialMonsterId,
      isFavorite: false,
      version: '1.0',
    );
  }

  /// Erstellt ein benutzerdefiniertes Creature
  static Creature createCustom({
    String? id,
    required String name,
    required int maxHp,
    int? currentHp,
    int armorClass = 10,
    String speed = "30ft",
    String attacks = "",
    int initiativeBonus = 0,
    int strength = 10,
    int dexterity = 10,
    int constitution = 10,
    int intelligence = 10,
    int wisdom = 10,
    int charisma = 10,
    bool isPlayer = false,
    List<Attack> attackList = const [],
    double gold = 0.0,
    double silver = 0.0,
    double copper = 0.0,
    String? size,
    String? type,
    String? subtype,
    String? alignment,
    int? challengeRating,
    String? specialAbilities,
    String? legendaryActions,
    String? description,
    String? sourceId,
    bool isFavorite = false,
    String version = '1.0',
  }) {
    return Creature(
      id: id ?? UuidService().generateId(),
      name: name,
      maxHp: maxHp,
      currentHp: currentHp ?? maxHp,
      armorClass: armorClass,
      speed: speed,
      attacks: attacks,
      initiativeBonus: initiativeBonus,
      isPlayer: isPlayer,
      strength: strength,
      dexterity: dexterity,
      constitution: constitution,
      intelligence: intelligence,
      wisdom: wisdom,
      charisma: charisma,
      attackList: attackList,
      gold: gold,
      silver: silver,
      copper: copper,
      size: size,
      type: type,
      subtype: subtype,
      alignment: alignment,
      challengeRating: challengeRating,
      specialAbilities: specialAbilities,
      legendaryActions: legendaryActions,
      description: description,
      isCustom: true,
      sourceType: 'custom',
      sourceId: sourceId,
      isFavorite: isFavorite,
      version: version,
    );
  }

  /// Erstellt ein NPC-Creature
  static Creature createNPC({
    String? id,
    required String name,
    required int maxHp,
    int armorClass = 10,
    String speed = "30ft",
    int strength = 10,
    int dexterity = 10,
    int constitution = 10,
    int intelligence = 10,
    int wisdom = 10,
    int charisma = 10,
    double gold = 0.0,
    double silver = 0.0,
    double copper = 0.0,
    String? description,
  }) {
    return Creature(
      id: id ?? UuidService().generateId(),
      name: name,
      maxHp: maxHp,
      currentHp: maxHp,
      armorClass: armorClass,
      speed: speed,
      isPlayer: false,
      strength: strength,
      dexterity: dexterity,
      constitution: constitution,
      intelligence: intelligence,
      wisdom: wisdom,
      charisma: charisma,
      gold: gold,
      silver: silver,
      copper: copper,
      description: description,
      isCustom: true,
      sourceType: 'custom',
      version: '1.0',
    );
  }
}
