// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJcbJjnRSSDKBX7fhw9Krj4q6M2jY1qN0',
    appId: '1:530188287523:web:e0697bbf5ff6510dbbbb96',
    messagingSenderId: '530188287523',
    projectId: 'dungoenmanager',
    authDomain: 'dungoenmanager.firebaseapp.com',
    storageBucket: 'dungoenmanager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8aXX8C3E0pAg7l9FDg5X61I1n2QIpcpk',
    appId: '1:530188287523:android:624e2c6969d19633bbbb96',
    messagingSenderId: '530188287523',
    projectId: 'dungoenmanager',
    storageBucket: 'dungoenmanager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcFoS7MXOSr6waCMbQ-ZwbbZ8TeZ7lHoo',
    appId: '1:530188287523:ios:d9a6db603ff1c9adbbbb96',
    messagingSenderId: '530188287523',
    projectId: 'dungoenmanager',
    storageBucket: 'dungoenmanager.firebasestorage.app',
    iosBundleId: 'com.example.hiveTestProjekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcFoS7MXOSr6waCMbQ-ZwbbZ8TeZ7lHoo',
    appId: '1:530188287523:ios:d9a6db603ff1c9adbbbb96',
    messagingSenderId: '530188287523',
    projectId: 'dungoenmanager',
    storageBucket: 'dungoenmanager.firebasestorage.app',
    iosBundleId: 'com.example.hiveTestProjekt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJcbJjnRSSDKBX7fhw9Krj4q6M2jY1qN0',
    appId: '1:530188287523:web:fd1eb988b380f854bbbb96',
    messagingSenderId: '530188287523',
    projectId: 'dungoenmanager',
    authDomain: 'dungoenmanager.firebaseapp.com',
    storageBucket: 'dungoenmanager.firebasestorage.app',
  );
}
