// lib/game_data/dnd_demo_data.dart
// Demo-Daten für D&D 5e Monster als Fallback, wenn externe Datenquellen nicht verfügbar

class DndDemoData {
  // Beispiel-Monster für Demo-Zwecke
  static final List<Map<String, dynamic>> demoMonsters = [
    {
      'id': 'goblin',
      'name': 'Goblin',
      'size': 'Small',
      'type': 'humanoid (goblinoid)',
      'subtype': null,
      'alignment': 'neutral evil',
      'armor_class': '15 (leather armor, shield)',
      'hit_points': 7,
      'hit_dice': '2d6',
      'speed': '30 ft.',
      'strength': 8,
      'dexterity': 14,
      'constitution': 10,
      'intelligence': 10,
      'wisdom': 8,
      'charisma': 8,
      'saving_throws': null,
      'skills': 'Stealth +6',
      'damage_vulnerabilities': null,
      'damage_resistances': null,
      'damage_immunities': null,
      'condition_immunities': null,
      'senses': 'darkvision 60 ft., passive Perception 9',
      'languages': 'Common, Goblin',
      'challenge_rating': 0.25,
      'xp': 50,
      'special_abilities': null,
      'actions': '''Scimitar. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage.
Shortbow. Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.''',
      'legendary_actions': null,
      'lair_actions': null,
      'description': 'Goblins are small, black-hearted, selfish humanoids that lair in caves, abandoned mines, despoiled dungeons, and other dismal settings.',
      'source': 'Monster Manual',
      'page': 166,
      'is_custom': 0,
      'version': '1.0',
    },
    {
      'id': 'orc',
      'name': 'Orc',
      'size': 'Medium',
      'type': 'humanoid (orc)',
      'subtype': null,
      'alignment': 'chaotic evil',
      'armor_class': '13 (hide armor)',
      'hit_points': 15,
      'hit_dice': '2d8 + 6',
      'speed': '30 ft.',
      'strength': 16,
      'dexterity': 12,
      'constitution': 16,
      'intelligence': 7,
      'wisdom': 11,
      'charisma': 10,
      'saving_throws': null,
      'skills': 'Intimidation +2',
      'damage_vulnerabilities': null,
      'damage_resistances': null,
      'damage_immunities': null,
      'condition_immunities': null,
      'senses': 'darkvision 60 ft., passive Perception 10',
      'languages': 'Common, Orcish',
      'challenge_rating': 0.5,
      'xp': 100,
      'special_abilities': '''Aggressive. As a bonus action, the orc can move up to its speed toward a hostile creature that it can see.''',
      'actions': '''Greataxe. Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12 + 3) slashing damage.
Javelin. Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 6 (1d6 + 3) piercing damage.''',
      'legendary_actions': null,
      'lair_actions': null,
      'description': 'Orcs are savage humanoids with stooped postures, low foreheads, and piggish faces with prominent lower canines that resemble tusks.',
      'source': 'Monster Manual',
      'page': 246,
      'is_custom': 0,
      'version': '1.0',
    },
    {
      'id': 'dragon_red_young',
      'name': 'Young Red Dragon',
      'size': 'Large',
      'type': 'dragon',
      'subtype': null,
      'alignment': 'chaotic evil',
      'armor_class': '17 (natural armor)',
      'hit_points': 178,
      'hit_dice': '17d10 + 85',
      'speed': '40 ft., climb 40 ft., fly 80 ft.',
      'strength': 23,
      'dexterity': 10,
      'constitution': 21,
      'intelligence': 14,
      'wisdom': 11,
      'charisma': 19,
      'saving_throws': 'Dex +4, Con +9, Wis +4, Cha +8',
      'skills': 'Perception +7, Stealth +4',
      'damage_vulnerabilities': null,
      'damage_resistances': null,
      'damage_immunities': 'fire',
      'condition_immunities': null,
      'senses': 'blindsight 30 ft., darkvision 120 ft., passive Perception 17',
      'languages': 'Common, Draconic',
      'challenge_rating': 10.0,
      'xp': 5900,
      'special_abilities': '''Amphibious. The dragon can breathe air and water.
Fire Aura. At the start of each of the dragon\'s turns, each creature within 10 feet of it takes 5 (1d10) fire damage, and flammable objects in the aura that aren\'t being worn or carried ignite. A creature that touches the dragon or hits it with a melee attack while within 5 feet of it takes 5 (1d10) fire damage.''',
      'actions': '''Multiattack. The dragon makes three attacks: one with its bite and two with its claws.
Bite. Melee Weapon Attack: +11 to hit, reach 10 ft., one target. Hit: 17 (2d10 + 6) piercing damage plus 5 (1d10) fire damage.
Claw. Melee Weapon Attack: +11 to hit, reach 5 ft., one target. Hit: 13 (2d6 + 6) slashing damage.
Fire Breath (Recharge 5-6). The dragon exhales fire in a 30-foot cone. Each creature in that area must make a DC 17 Dexterity saving throw, taking 56 (16d6) fire damage on a failed save, or half as much damage on a successful one.''',
      'legendary_actions': null,
      'lair_actions': null,
      'description': 'A young red dragon has bright red scales that shine like wet coals. Its eyes glow orange, and its horns and spine are jet black.',
      'source': 'Monster Manual',
      'page': 91,
      'is_custom': 0,
      'version': '1.0',
    },
    {
      'id': 'skeleton',
      'name': 'Skeleton',
      'size': 'Medium',
      'type': 'undead',
      'subtype': null,
      'alignment': 'lawful evil',
      'armor_class': '13 (armor scraps)',
      'hit_points': 13,
      'hit_dice': '2d8 + 4',
      'speed': '30 ft.',
      'strength': 10,
      'dexterity': 14,
      'constitution': 15,
      'intelligence': 6,
      'wisdom': 8,
      'charisma': 5,
      'saving_throws': null,
      'skills': 'Stealth +4',
      'damage_vulnerabilities': 'bludgeoning',
      'damage_resistances': null,
      'damage_immunities': 'poison',
      'condition_immunities': 'poisoned',
      'senses': 'darkvision 60 ft., passive Perception 9',
      'languages': 'understands all languages it knew in life but can\'t speak',
      'challenge_rating': 0.25,
      'xp': 50,
      'special_abilities': null,
      'actions': '''Shortsword. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.
Shortbow. Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.''',
      'legendary_actions': null,
      'lair_actions': null,
      'description': 'Skeletons are the animated bones of the dead, mindless automatons that obey the orders of their evil masters.',
      'source': 'Monster Manual',
      'page': 272,
      'is_custom': 0,
      'version': '1.0',
    },
    {
      'id': 'zombie',
      'name': 'Zombie',
      'size': 'Medium',
      'type': 'undead',
      'subtype': null,
      'alignment': 'neutral evil',
      'armor_class': '8',
      'hit_points': 22,
      'hit_dice': '3d8 + 9',
      'speed': '20 ft.',
      'strength': 13,
      'dexterity': 6,
      'constitution': 16,
      'intelligence': 3,
      'wisdom': 6,
      'charisma': 5,
      'saving_throws': null,
      'skills': null,
      'damage_vulnerabilities': null,
      'damage_resistances': null,
      'damage_immunities': 'poison',
      'condition_immunities': 'poisoned',
      'senses': 'darkvision 60 ft., passive Perception 8',
      'languages': 'understands the languages it knew in life but can\'t speak',
      'challenge_rating': 0.25,
      'xp': 50,
      'special_abilities': '''Undead Fortitude. If damage reduces the zombie to 0 hit points, it must make a Constitution saving throw with a DC of 5 + the damage taken, unless the damage is radiant or from a critical hit. On a success, the zombie drops to 1 hit point instead.''',
      'actions': '''Slam. Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) bludgeoning damage.''',
      'legendary_actions': null,
      'lair_actions': null,
      'description': 'Zombies are undead corpses animated by dark magic. They shamble about mindlessly, attacking living creatures that cross their path.',
      'source': 'Monster Manual',
      'page': 316,
      'is_custom': 0,
      'version': '1.0',
    },
  ];

  // Beispiel-Zauber für Demo-Zwecke
  static final List<Map<String, dynamic>> demoSpells = [
    {
      'id': 'magic_missile',
      'name': 'Magic Missile',
      'level': 1,
      'school': 'Evocation',
      'ritual': 0,
      'casting_time': '1 action',
      'range': '120 feet',
      'duration': 'Instantaneous',
      'components': 'V, S',
      'materials': null,
      'description': 'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.',
      'higher_levels': 'When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.',
      'classes': 'Wizard',
      'source': 'Player\'s Handbook',
      'page': 257,
      'is_custom': 0,
      'version': '1.0',
    },
    {
      'id': 'fireball',
      'name': 'Fireball',
      'level': 3,
      'school': 'Evocation',
      'ritual': 0,
      'casting_time': '1 action',
      'range': '150 feet',
      'duration': 'Instantaneous',
      'components': 'V, S, M',
      'materials': 'a tiny ball of bat guano and sulfur',
      'description': 'A bright streak flashes from your pointing finger to a point you choose within range then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.',
      'higher_levels': 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
      'classes': 'Wizard, Sorcerer',
      'source': 'Player\'s Handbook',
      'page': 241,
      'is_custom': 0,
      'version': '1.0',
    },
  ];

  // Beispiel-Klassen für Demo-Zwecke
  static final List<Map<String, dynamic>> demoClasses = [
    {
      'id': 'fighter',
      'name': 'Fighter',
      'hit_die': '1d10',
      'proficiency_choices': null,
      'starting_proficiencies': null,
      'equipment': null,
      'class_table': null,
      'spellcasting': null,
      'features': null,
      'subclasses': null,
      'source': 'Player\'s Handbook',
      'page': 70,
      'is_custom': 0,
      'version': '1.0',
    },
    {
      'id': 'wizard',
      'name': 'Wizard',
      'hit_die': '1d6',
      'proficiency_choices': null,
      'starting_proficiencies': null,
      'equipment': null,
      'class_table': null,
      'spellcasting': null,
      'features': null,
      'subclasses': null,
      'source': 'Player\'s Handbook',
      'page': 112,
      'is_custom': 0,
      'version': '1.0',
    },
  ];

  // Beispiel-Völker für Demo-Zwecke
  static final List<Map<String, dynamic>> demoRaces = [
    {
      'id': 'human',
      'name': 'Human',
      'ability_bonuses': null,
      'age': null,
      'alignment': null,
      'size': 'Medium',
      'speed': null,
      'languages': null,
      'traits': null,
      'subraces': null,
      'source': 'Player\'s Handbook',
      'page': 29,
      'is_custom': 0,
      'version': '1.0',
    },
    {
      'id': 'elf',
      'name': 'Elf',
      'ability_bonuses': null,
      'age': null,
      'alignment': null,
      'size': 'Medium',
      'speed': null,
      'languages': null,
      'traits': null,
      'subraces': null,
      'source': 'Player\'s Handbook',
      'page': 23,
      'is_custom': 0,
      'version': '1.0',
    },
  ];

  // Beispiel-Items für Demo-Zwecke
  static final List<Map<String, dynamic>> demoItems = [
    {
      'id': 'longsword',
      'name': 'Longsword',
      'item_type': 'martial melee weapon',
      'rarity': null,
      'requires_attunement': 0,
      'weight': 3.0,
      'cost': 15.0,
      'weapon_category': null,
      'weapon_range': null,
      'damage': null,
      'properties': null,
      'armor_category': null,
      'armor_class': null,
      'stealth_disadvantage': 0,
      'strength_requirement': null,
      'description': 'A longsword is a martial melee weapon. It deals 1d8 slashing damage, or 1d10 when used with two hands.',
      'source': 'Player\'s Handbook',
      'page': 149,
      'is_custom': 0,
      'version': '1.0',
    },
    {
      'id': 'leather_armor',
      'name': 'Leather Armor',
      'item_type': 'light armor',
      'rarity': null,
      'requires_attunement': 0,
      'weight': 10.0,
      'cost': 10.0,
      'weapon_category': null,
      'weapon_range': null,
      'damage': null,
      'properties': null,
      'armor_category': null,
      'armor_class': '11 + Dex modifier',
      'stealth_disadvantage': 0,
      'strength_requirement': null,
      'description': 'Leather armor is made of tough but flexible leather. It offers 11 + Dex modifier AC and doesn\'t impose disadvantage on Stealth checks.',
      'source': 'Player\'s Handbook',
      'page': 145,
      'is_custom': 0,
      'version': '1.0',
    },
  ];

  // Beispiel-Orte für Demo-Zwecke
  static final List<Map<String, dynamic>> demoLocations = [
    {
      'id': 'waterdeep',
      'name': 'Waterdeep',
      'location_type': 'City',
      'description': 'Waterdeep, also known as the City of Splendors or the Crown of the North, is the most important and influential city in the North and perhaps in all Faerûn.',
      'region': 'Sword Coast',
      'parent_location_id': null,
      'coordinates': null,
      'notable_npcs': null,
      'notable_locations': null,
      'quests': null,
      'encounters': null,
      'source': 'Sword Coast Adventurer\'s Guide',
      'page': 108,
      'is_custom': 0,
      'version': '1.0',
    },
    {
      'id': 'neverwinter',
      'name': 'Neverwinter',
      'location_type': 'City',
      'description': 'Neverwinter, also known as the City of Skilled Hands or the Jewel of the North, is a metropolis sitting on the northwestern coast of the Inner Sea.',
      'region': 'Sword Coast',
      'parent_location_id': null,
      'coordinates': null,
      'notable_npcs': null,
      'notable_locations': null,
      'quests': null,
      'encounters': null,
      'source': 'Sword Coast Adventurer\'s Guide',
      'page': 104,
      'is_custom': 0,
      'version': '1.0',
    },
  ];
}
